package com.hms.queue;
import com.hms.appointments.*; import com.hms.doctors.*; import com.hms.tenancy.*; import jakarta.validation.Valid; import java.time.LocalDate; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/hospitals/{tenantSlug}/queue") public class QueueTokenController{
 private final TenantRepository tenants; private final AppointmentRepository appointments; private final DoctorRepository doctors; private final QueueTokenRepository tokens;
 public QueueTokenController(TenantRepository t,AppointmentRepository a,DoctorRepository d,QueueTokenRepository q){tenants=t;appointments=a;doctors=d;tokens=q;}
 @GetMapping("/doctors/{doctorId}") public List<QueueToken> list(@PathVariable String tenantSlug,@PathVariable UUID doctorId,@RequestParam LocalDate date){UUID t=tenant(tenantSlug);doctor(doctorId,t);return tokens.findAllByTenantIdAndDoctorIdAndTokenDateOrderByPriorityDescTokenNumberAsc(t,doctorId,date);}
 @PostMapping("/appointments/{appointmentId}/token") @ResponseStatus(HttpStatus.CREATED) public QueueToken create(@PathVariable String tenantSlug,@PathVariable UUID appointmentId){UUID t=tenant(tenantSlug);Appointment a=appointments.findById(appointmentId).orElseThrow(()->new IllegalArgumentException("Appointment not found"));if(!a.getTenantId().equals(t))throw new IllegalArgumentException("Appointment does not belong to hospital");if(a.getStatus()!=AppointmentStatus.CHECKED_IN)throw new IllegalArgumentException("Appointment must be checked in before token creation");if(tokens.findByAppointmentId(appointmentId).isPresent())throw new IllegalArgumentException("Appointment already has a token");LocalDate date=a.getStartsAt().toLocalDate();int number=tokens.findFirstByTenantIdAndDoctorIdAndTokenDateOrderByTokenNumberDesc(t,a.getDoctorId(),date).map(x->x.getTokenNumber()+1).orElse(1);return tokens.save(new QueueToken(t,appointmentId,a.getDoctorId(),date,number));}
 @PatchMapping("/{tokenId}/priority") public QueueToken prioritize(@PathVariable String tenantSlug,@PathVariable UUID tokenId,@Valid @RequestBody CreateTokenPriorityRequest request){QueueToken token=tokens.findById(tokenId).orElseThrow(()->new IllegalArgumentException("Token not found"));if(!token.getTenantId().equals(tenant(tenantSlug)))throw new IllegalArgumentException("Token does not belong to hospital");token.prioritize(request.reason(),request.note());return tokens.save(token);}
 private UUID tenant(String s){return tenants.findBySlug(s).map(Tenant::getId).orElseThrow(()->new TenantNotFoundException(s));} private void doctor(UUID d,UUID t){Doctor x=doctors.findById(d).orElseThrow(()->new IllegalArgumentException("Doctor not found"));if(!x.getTenantId().equals(t))throw new IllegalArgumentException("Doctor does not belong to hospital");}
}
