package com.hms.queue;
import jakarta.persistence.*; import java.time.*; import java.util.UUID;
@Entity @Table(name="queue_tokens") public class QueueToken {
 @Id private UUID id; @Column(nullable=false) private UUID tenantId; @Column(nullable=false) private UUID appointmentId; @Column(nullable=false) private UUID doctorId; @Column(nullable=false) private LocalDate tokenDate; @Column(nullable=false) private int tokenNumber; @Enumerated(EnumType.STRING) @Column(nullable=false) private TokenStatus status; @Column(nullable=false) private boolean priority; @Enumerated(EnumType.STRING) private PriorityReason priorityReason; @Column(length=500) private String priorityNote; @Column(nullable=false) private OffsetDateTime createdAt; @Column(nullable=false) private OffsetDateTime updatedAt;
 protected QueueToken(){} public QueueToken(UUID tenantId,UUID appointmentId,UUID doctorId,LocalDate date,int number){this.id=UUID.randomUUID();this.tenantId=tenantId;this.appointmentId=appointmentId;this.doctorId=doctorId;this.tokenDate=date;this.tokenNumber=number;this.status=TokenStatus.WAITING;this.createdAt=OffsetDateTime.now();this.updatedAt=createdAt;}
 public void prioritize(PriorityReason reason,String note){if(reason==null)throw new IllegalArgumentException("Priority reason is required");this.priority=true;this.priorityReason=reason;this.priorityNote=note;this.updatedAt=OffsetDateTime.now();}
 public void updateStatus(TokenStatus next){if(status==TokenStatus.COMPLETED||status==TokenStatus.CANCELLED)throw new IllegalArgumentException("Token is already closed");if(next==TokenStatus.WAITING&&status!=TokenStatus.HELD)throw new IllegalArgumentException("Only held tokens can return to waiting");this.status=next;this.updatedAt=OffsetDateTime.now();}
 public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getAppointmentId(){return appointmentId;} public UUID getDoctorId(){return doctorId;} public LocalDate getTokenDate(){return tokenDate;} public int getTokenNumber(){return tokenNumber;} public TokenStatus getStatus(){return status;} public boolean isPriority(){return priority;} public PriorityReason getPriorityReason(){return priorityReason;} public String getPriorityNote(){return priorityNote;}
}
