package com.hms.queue;
import com.hms.appointments.*; import com.hms.doctors.*; import com.hms.tenancy.*; import jakarta.validation.Valid; import java.time.LocalDate; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*;
import com.hms.audit.AuditLog; import com.hms.audit.AuditLogRepository;
@RestController @RequestMapping("/api/hospitals/{tenantSlug}/queue") public class QueueTokenController{
 private final TenantRepository tenants; private final AppointmentRepository appointments; private final DoctorRepository doctors; private final QueueTokenRepository tokens; private final AuditLogRepository auditLogs;
 public QueueTokenController(TenantRepository t,AppointmentRepository a,DoctorRepository d,QueueTokenRepository q,AuditLogRepository auditLogs){tenants=t;appointments=a;doctors=d;tokens=q;this.auditLogs=auditLogs;}
 @GetMapping("/doctors/{doctorId}") public List<QueueTokenDto> list(@PathVariable String tenantSlug,@PathVariable UUID doctorId,@RequestParam LocalDate date){UUID t=tenant(tenantSlug);doctor(doctorId,t);return tokens.findAllByTenantIdAndDoctorIdAndTokenDateOrderByPriorityDescTokenNumberAsc(t,doctorId,date).stream().map(QueueTokenDto::from).toList();}
 @PostMapping("/appointments/{appointmentId}/token") @ResponseStatus(HttpStatus.CREATED) public QueueToken create(@PathVariable String tenantSlug,@PathVariable UUID appointmentId){UUID t=tenant(tenantSlug);Appointment a=appointments.findById(appointmentId).orElseThrow(()->new IllegalArgumentException("Appointment not found"));if(!a.getTenantId().equals(t))throw new IllegalArgumentException("Appointment does not belong to hospital");if(a.getStatus()!=AppointmentStatus.CHECKED_IN)throw new IllegalArgumentException("Appointment must be checked in before token creation");if(tokens.findByAppointmentId(appointmentId).isPresent())throw new IllegalArgumentException("Appointment already has a token");LocalDate date=a.getStartsAt().toLocalDate();int number=tokens.findFirstByTenantIdAndDoctorIdAndTokenDateOrderByTokenNumberDesc(t,a.getDoctorId(),date).map(x->x.getTokenNumber()+1).orElse(1);return tokens.save(new QueueToken(t,appointmentId,a.getDoctorId(),date,number));}
 @PatchMapping("/{tokenId}/priority") public QueueToken prioritize(@PathVariable String tenantSlug,@PathVariable UUID tokenId,@Valid @RequestBody CreateTokenPriorityRequest request){QueueToken token=tokens.findById(tokenId).orElseThrow(()->new IllegalArgumentException("Token not found"));UUID t=tenant(tenantSlug);if(!token.getTenantId().equals(t))throw new IllegalArgumentException("Token does not belong to hospital");String previous=token.getStatus().name()+"/"+token.isPriority();token.prioritize(request.reason(),request.note());QueueToken saved=tokens.save(token);auditLogs.save(new AuditLog(t,"TOKEN_PRIORITIZED","QUEUE_TOKEN",tokenId.toString(),"previous="+previous+",new=priority,reason="+request.reason()+",note="+request.note()+",appointment="+token.getAppointmentId()));return saved;}
 @PatchMapping("/{tokenId}/status") public QueueToken updateStatus(@PathVariable String tenantSlug,@PathVariable UUID tokenId,@Valid @RequestBody UpdateTokenStatusRequest request){QueueToken token=tokens.findById(tokenId).orElseThrow(()->new IllegalArgumentException("Token not found"));if(!token.getTenantId().equals(tenant(tenantSlug)))throw new IllegalArgumentException("Token does not belong to hospital");token.updateStatus(request.status());return tokens.save(token);}
 private UUID tenant(String s){return tenants.findBySlug(s).map(Tenant::getId).orElseThrow(()->new TenantNotFoundException(s));} private void doctor(UUID d,UUID t){Doctor x=doctors.findById(d).orElseThrow(()->new IllegalArgumentException("Doctor not found"));if(!x.getTenantId().equals(t))throw new IllegalArgumentException("Doctor does not belong to hospital");}
}
